project:
  type: website
  output-dir: docs

metadata-files:
  - _sidebar.yml

website:
  navbar:
    page_navigation: true
    favicon: "figures/pyfixest-logo.png"
    page-footer:
      center: |
        Developed by [Alexander Fischer](https://github.com/s3alfisc) and [Styfen Schär](https://github.com/styfenschaer)
    search: true
    right:
      - icon: github
        href: https://github.com/s3alfisc/pyfixest/
    left:
      - text: "PyFixest"
        file: readme.qmd
      #- text: "Tutorial"
      #  file: docs/notebooks/tutorial.qmd
      #- text: "Difference-in-Differences Estimation"
      #  file: difference-in-differences-estimation.ipynb
      #- text "Replicating 'The Effect' with PyFixest"
      #  file: docs/Replicating-the-Effect.ipynb
      - text: "Function Reference"
        file: reference/index.qmd
      #- text: "Changelog"
      #  file: news.qmd

quartodoc:
  package: pyfixest

  sidebar: _sidebar.yml

  sections:
    - title: For Users
      desc: |
        User facing estimation functions
      contents:
        - estimation.feols
        - estimation.fepois
        - did.estimation.did2s
        - did.estimation.lpdid
        #- did.estimation.event_study
    - title: Summarize and Visualize
      desc: |
        Post-Processing of Estimation Results
      contents:
        - summarize.summary
        - summarize.etable
        - visualize.coefplot
        - visualize.iplot
    #- title: Estimation Classes
      #desc: |
      #  Details on Methods and Attributes
      #contents:
        #- feols
        #- fepois
        #- did.DID
        #- did.did2s
        #- did.lpdid
        #- did.twfe
    - title: For Developers
      desc: |
        PyFixest internals and utilities
      contents:
        - demean
        - detect_singletons