project:
  type: website
  output-dir: docs

metadata-files:
  - _sidebar.yml

website:
  navbar:
    page_navigation: true
    #favicon: "figures/pyfixest-logo.png"
    #page-footer:
    #  center: |
    #    Developed by [Alexander Fischer](https://github.com/s3alfisc) and [Styfen Schär](https://github.com/styfenschaer)
    search: true
    right:
      - icon: github
        href: https://github.com/s3alfisc/pyfixest/
    left:
      - text: "PyFixest"
        file: ./readme2.md
      - text: "Quickstart"
        file: ./vignettes/quickstart2.ipynb
      - text: "Difference-in-Differences Estimation"
        file: ./vignettes/difference-in-differences2.ipynb
      - text: "Replicating 'The Effect' with PyFixest"
        file: ./vignettes/replicating-the-effect2.ipynb
      - text: "Documentation"
        file: reference/index.qmd
      - text: "Changelog"
        file: ./vignettes/news2.qmd

quartodoc:
  package: pyfixest

  sidebar: _sidebar.yml

  sections:
    - title: Estimation Functions
      desc: |
        User facing estimation functions
      contents:
        - estimation.feols
        - estimation.fepois
        - did.estimation.did2s
        - did.estimation.lpdid
        - did.estimation.event_study
    - title: Estimation Classes
      desc: |
        Details on Methods and Attributes
      contents:
        - feols
        - fepois
        - feiv
        #- did.DID
        #- did.did2s
        #- did.lpdid
        #- did.twfe
    - title: Summarize and Visualize
      desc: |
        Post-Processing of Estimation Results
      contents:
        - summarize.summary
        - summarize.etable
        - visualize.coefplot
        - visualize.iplot
    - title: Misc / Utilities
      desc: |
        PyFixest internals and utilities
      contents:
        - demean
        - detect_singletons
        - model_matrix_fixest