project:
  type: website

metadata-files:
  - _sidebar.yml

website:
  navbar:
<<<<<<< HEAD
    #page_navigation: true
=======
    page_navigation: true
>>>>>>> 2161d2b204a69c8ae5ddfd8697ace7a24fe872ee
    #favicon: "figures/pyfixest-logo.png"
    #page-footer:
      #center: |
      #  Developed by
      #    [Alexander Fischer](https://github.com/s3alfisc) and [Styfen Schär](https://github.com/styfenschaer)
    search: true
    right:
      - icon: github
        href: https://github.com/s3alfisc/pyfixest/
    left:
      - text: "Home"
<<<<<<< HEAD
        file: readme.md
      #- text: "Tutorial"
      #  file: docs/tutorial.ipynb
      #- text: "Difference-in-Differences Estimation"
      #  file: docs/difference-in-differences-estimation.ipynb
      #- text: "News"
      #  file: docs/news.md
=======
        file: docs/index.ipynb
      - text: "Tutorial"
        file: docs/tutorial.ipynb
      - text: "Difference-in-Differences Estimation"
        file: docs/difference-in-differences-estimation.ipynb
      - text: "News"
        file: docs/news.md
>>>>>>> 2161d2b204a69c8ae5ddfd8697ace7a24fe872ee
      - text: "Reference"
        file: reference/index.qmd

quartodoc:
  package: pyfixest

  sidebar: _sidebar.yml

  sections:
<<<<<<< HEAD
    - title: For Users
      desc: |
        User facing estimation functions
      contents:
        # - estimation.feols
        - estimation.fepois
        #- did.estimation.did2s
        #- did.estimation.lpdid
        #- did.estimation.event_study
    - title: Summarize and Visualize
      desc: |
        Post-Processing of Estimation Results
      contents:
        - summarize.summary
        - summarize.etable
        - visualize.coefplot
        - visualize.iplot
    - title: Estimation Classes
      desc: |
        Details on Methods and Attributes
      contents:
        #- feols
        #- fepois
        - did.did
        - did.did2s
        - did.lpdid
        - did.twfe
    - title: For Developers
      desc: |
        PyFixest internals and utilities
      contents:
        - demean.demean
        - detect_singletons.detect_singletons
        - model_matrix_fixest
=======
    #- title: For Users
    #  desc: User facing estimation functions
    #  contents:
      #  - estimation.feols
      #  - estimation.fepois
      # - did.estimation.did2s
        #- did.estimation.lpdid
        #- did.estimation.event_study
    - title: For Developers
      desc: PyFixest internals and utilities
      contents:
        - demean
    #    #- detect_singletons.detect_singletons
>>>>>>> 2161d2b204a69c8ae5ddfd8697ace7a24fe872ee
