ignore:
  - "benchmarks/**"
  - "pyfixest/utils/dgps.py"
  - "pyfixest/utils/_exceptions.py"

flags:
  tests-nojit:
    paths:
      - "pyfixest/estimation/numba/*"
    carryforward: true

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 2%
        base: auto
        paths:
          - "pyfixest"
        # advanced settings
        branches:
          - master
        if_ci_failed: error
        informational: false
        only_pulls: false

comment:
  show_diff_only: false
