---
title: "Tesdt"
author: "Alexander Fischer"
date: "2023-07-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{python}

import pyfixest as pf
from pyfixest.utils import get_data, get_poisson_data
from pyfixest.ssc_utils import ssc
import numpy as np
import pandas as pd

data =  get_poisson_data(N = 100_000, seed = 98282)
data = data.dropna()
data.dtypes
data["group"] = pd.Categorical(np.random.choice(list(range(100)), 100_000, True))

fixest = pf.Fixest(data = data)

# fml = "Y~ X1 + X2| fe1 + fe2"
# depvar = "Y"
# covar = "X1 + X2"
# fval = "fe1 + fe2"
# 
# vcov = 'iid'

#fixest.fepois(fml = "Y~ X1 + X2| group^X4 ", vcov = "hetero")
fixest.feols(fml = "Y~ X1 + X2| group", vcov = "hetero")
fixest.tidy()
#data.head()
fixest.tstat()

mod = fixest.fetch_model("0")
coef = mod.beta_hat
u_hat = mod.u_hat
se = mod._se
conf_int = mod.conf_int

u_hat = mod.resid().flatten() # array([  -35.79395865,  -975.93621725, -1319.89258669, 
y_hat = mod.predict().flatten() 
coef = mod.coef().values # array([671.37477031,  29.59796266])
mod.fixef()
sumFE = mod.sumFE

#mod.fixef()
# value  631.25713  827.996321  693.886165  ...  611.827561  762.843813  558.500829
mod.fixef_dict

mod
mod.fixef()
fixef_dict = mod.fixef_dict


```

```{r}
library(reticulate)
library(fixest)

data = py$data
data$group <- as.factor(data$group)
residual <- py$residual
yhat <- py$yhat
coef <- py$coef


fit = feols(Y~ X1 + X2| group , data = data, se = "hetero")
all.equal(c(py$coef), coef(fit), check.attributes = FALSE)
all.equal(c(py$u_hat), resid(fit), check.attributes = FALSE)
all.equal(c(py$y_hat), predict(fit), check.attributes = FALSE)
all.equal(c(py$y_hat), fit$sumFE, check.attributes = FALSE)

fixef(fit) |> head()
py$fixef_dict

fixest::tstat(fit)



resid(fit) |> head()
predict(fit) |> head()
fixef(fit) |> head()

confint(fit) |> head()
se(fit)

coef(fit)

fixef(fit) 
predict(fit) |> head()
resid(fit) |> head()
(data$Y - resid(fit)) |> head()

```




```{python}
import pyfixest as pf
from pyfixest.utils import get_data, get_poisson_data
from pyfixest.ssc_utils import ssc
import numpy as np
import pandas as pd


y = np.array([0, 0, 0, 1, 2, 3])
df1 = np.array(["a", "a", "b", "b", "b", "c"])
df2 = np.array(["c", "c", "d", "d", "d", "e"])
x = np.random.normal(0, 1, 6)

df = pd.DataFrame({"Y": y, "fe1": df1, "fe2": df2, "x" : x})
df

self = pf.Fixest(data = df)
self.fepois("Y ~ x  | fe1", vcov = "hetero")
self = self.fetch_model(0)
self._check_for_separation()


```




# Poisson: test R against fixest


```{python}
import numpy as np
from numpy import log
import pandas as pd
from pyfixest.fixest import Fixest
from pyfixest.utils import get_data, get_poisson_data
from pyfixest.ssc_utils import ssc

def data_poisson():
    return get_poisson_data(N = 10_000,seed = 6574)
  
data = data_poisson()

py_ci
mod = pyfixest.fetch_model(0).confint()

  
fml = "Y~X1+X2"

pyfixest = Fixest(data = data).feols(fml, vcov = {'CRV1':'X4'}, ssc = ssc(adj = False, cluster_adj = False))

py_coef = (pyfixest.coef())
py_se = (pyfixest.se())
py_pval = (pyfixest.pvalue())
py_tstat = (pyfixest.tstat())
py_ci = pyfixest.confint()

y = np.array([  0.000000e+00, 3.865329e-70, 1.082498e-01  ])
x = py_pval.values



```




```{r}
library(reticulate)
library(fixest)

data = py$data
py_coef = py$py_coef
py_se = py$py_se
py_pval = py$py_pval
py_tstat = py$py_tstat
py_ci = py$py_ci


fml = as.formula(py$fml)


fit = feols(fml, data = data, cluster = ~X4, ssc = ssc(adj = FALSE, cluster.adj = FALSE))

cbind(coef(fit), py_coef)
cbind(se(fit), py_se)
cbind(pvalue(fit), py_pval)
cbind(tstat(fit), py_tstat)

r_ci = confint(fit)
py_ci == r_ci



any(abs(se(fit) -  py_se) > 1e-04)
any(abs(pvalue(fit) -  py_pval) > 1e-04)

relative_diff = any(abs(tstat(fit) -  py_tstat) > 1e-04)
absolute_diff = any(abs(tstat(fit) -  py_tstat) / abs(py_tstat) > 1e-04)



```
























