site_name: PyFixest

theme:
  name: "mkdocs"

plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      execute: true

nav:
  - index.ipynb
  - tutorial.ipynb
  - Replicating-the-Effect.ipynb
  - reference.md


