# visualize.iplot { #pyfixest.visualize.iplot }

`visualize.iplot(models, alpha=0.05, figsize=(500, 300), yintercept=None, xintercept=None, rotate_xticks=0, title=None, coord_flip=True)`

Plot model coefficients for variables interacted via "i()" syntax, with confidence intervals.

## Parameters

| Name            | Type           | Description                                                                                            | Default      |
|-----------------|----------------|--------------------------------------------------------------------------------------------------------|--------------|
| `models`        | list or object | A list of fitted models of type [Feols(/docs/reference/Feols.qmd) or `Fepois`, or just a single model. | _required_   |
| `figsize`       | tuple          | The size of the figure.                                                                                | `(500, 300)` |
| `alpha`         | float          | The significance level for the confidence intervals.                                                   | `0.05`       |
| `yintercept`    | int or None    | The value at which to draw a horizontal line on the plot.                                              | `None`       |
| `xintercept`    | int or None    | The value at which to draw a vertical line on the plot.                                                | `None`       |
| `rotate_xticks` | float          | The angle in degrees to rotate the xticks labels. Default is 0 (no rotation).                          | `0`          |
| `title`         | str            | The title of the plot.                                                                                 | `None`       |
| `coord_flip`    | bool           | Whether to flip the coordinates of the plot. Default is True.                                          | `True`       |

## Returns

| Type   | Description         |
|--------|---------------------|
| object | A lets-plot figure. |

## Examples

```{python}
from pyfixest.utils import get_data
from pyfixest.estimation import feols
from pyfixest.visualize import iplot

df = get_data()
fit1 = feols("Y ~ i(f1)", data = df)
fit2 = feols("Y ~ i(f1) + X2", data = df)
fit3 = feols("Y ~ i(f1) + X2 | f2", data = df)

iplot([fit1, fit2, fit3])
```