# demean { #pyfixest.demean }

`demean`



## Functions

| Name | Description |
| --- | --- |
| [demean](#pyfixest.demean.demean) | Workhorse for demeaning an input array `x` based on the specified fixed effects and weights |
| [demean_model](#pyfixest.demean.demean_model) | Demeans a single regression model via the alterating projections algorithm (see `demean` function). |

### demean { #pyfixest.demean.demean }

`demean.demean(x, flist, weights, tol=1e-08, maxiter=100000)`

Workhorse for demeaning an input array `x` based on the specified fixed effects and weights
via the alternating projections algorithm.

#### Parameters

| Name      | Type                | Description                                                                                                    | Default    |
|-----------|---------------------|----------------------------------------------------------------------------------------------------------------|------------|
| `x`       | numpy.numpy.ndarray | Input array of shape (n_samples, n_features). Needs to be of type float.                                       | _required_ |
| `flist`   | numpy.numpy.ndarray | Array of shape (n_samples, n_factors) specifying the fixed effects. Needs to already be converted to integers. | _required_ |
| `weights` | numpy.numpy.ndarray | Array of shape (n_samples,) specifying the weights.                                                            | _required_ |
| `tol`     | float               | Tolerance criterion for convergence. Defaults to 1e-08.                                                        | `1e-08`    |
| `maxiter` | int                 | Maximum number of iterations. Defaults to 100_000.                                                             | `100000`   |

#### Returns

| Type                                      | Description                                                                                                                                   |
|-------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| typing.Tuple\[numpy.numpy.ndarray, bool\] | A tuple containing the demeaned array of shape (n_samples, n_features) and a boolean indicating whether the algorithm converged successfully. |

### demean_model { #pyfixest.demean.demean_model }

`demean.demean_model(Y, X, fe, weights, lookup_demeaned_data, na_index_str)`

Demeans a single regression model via the alterating projections algorithm (see `demean` function).
Prior to demeaning, the function checks if some of the variables have already been demeaned and uses values
from the cache `lookup_demeaned_data` if possible. If the model has no fixed effects, the function does not demean the data.

#### Parameters

| Name                   | Type                            | Description                                                                                                                                                                                               | Default    |
|------------------------|---------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `Y`                    | pandas.pandas.DataFrame         | A DataFrame of the dependent variable.                                                                                                                                                                    | _required_ |
| `X`                    | pandas.pandas.DataFrame         | A DataFrame of the covariates.                                                                                                                                                                            | _required_ |
| `fe`                   | pandas.pandas.DataFrame or None | A DataFrame of the fixed effects. None if no fixed effects specified.                                                                                                                                     | _required_ |
| `weights`              | numpy.numpy.ndarray or None     | A numpy array of weights. None if no weights.                                                                                                                                                             | _required_ |
| `lookup_demeaned_data` | typing.Dict\[str, typing.Any\]  | A dictionary with keys for each fixed effects combination and potentially values of demeaned data frames. The function checks this dictionary to see if some of the variables have already been demeaned. | _required_ |
| `na_index_str`         | str                             | A string with indices of dropped columns. Used for caching of demeaned variables.                                                                                                                         | _required_ |

#### Returns

| Type                                                                                                         | Description                                                                                                                                                                                                                                                        |
|--------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| typing.Tuple\[pandas.pandas.DataFrame, pandas.pandas.DataFrame, typing.Optional\[pandas.pandas.DataFrame\]\] | A tuple of the following elements: - Yd : pd.DataFrame     A DataFrame of the demeaned dependent variable. - Xd : pd.DataFrame     A DataFrame of the demeaned covariates. - Id : pd.DataFrame or None     A DataFrame of the demeaned Instruments. None if no IV. |