# summarize.etable { #pyfixest.summarize.etable }

`summarize.etable(models, digits=3, type='md', signif_code=[0.001, 0.01, 0.05], coef_fmt='b (se)')`

    Create an esttab-like table from a list of models.

    Parameters
    ----------
    models : list
        A list of models of type Feols, Feiv, Fepois.
    digits : int
        Number of digits to round to.
    type : str, optional
        Type of output. Either "df" for pandas DataFrame, "md" for markdown, or "tex" for LaTeX table. Default is "md".
    signif_code : list, optional
        Significance levels for the stars. Default is [0.001, 0.01, 0.05]. If None, no stars are printed.
    coef_fmt : str, optional
        The format of the coefficient (b), standard error (se), t-stats (t), and p-value (p). Default is "b (se)".
        Spaces ` `, parentheses `()`, brackets `[]`, newlines `
` are supported.
        Newline is not support for LaTeX output.

    Returns
    -------
    pandas.DataFrame
        A DataFrame with the coefficients and standard errors of the models.

    Examples
    --------

    ```{python}
    from pyfixest.estimation import feols
    from pyfixest.utils import get_data
    from pyfixest.summarize import etable

    # load data
    df = get_data()
    fit1 = feols("Y~X1 + X2 | f1", df)
    fit2 = feols("Y~X1 + X2 | f1 + f2", df)
    fit3 = feols("Y~X1 + X2 | f1 + f2 + f3", df)

    etable([fit1, fit2, fit3])
    etable([fit1, fit2, fit3], type="df")
    etable([fit1, fit2, fit3], signif_code=[0.01, 0.05, 0.1])
    ```