name: Extended Tests (Optional)

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-extended:
    name: "Tests Python Extended"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: v0.62.2
          cache: true
          cache-write: true
          frozen: true
          environments: py312

      - name: Run extended tests
        run: pixi run -e py312 test-py-extended
        env:
          PYTEST_XDIST_AUTO_NUM_WORKERS: 4

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: tests-extended
