name: Release Drafter

on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
